import { AppProvider } from '@/providers';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const baseApiUrl = process.env.BASE_API_URL ?? '';
  const useMockData = process.env.USE_MOCK_DATA === 'true';

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider baseApiUrl={baseApiUrl} useMockData={useMockData}>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
